version: "3.8"
services:
  webserver:
    image: apache/airflow:2.0.0b3-python3.7
    entrypoint: bash
    command: /opt/airflow/startup.bash webserver
    deploy:
      replicas: 1      
      restart_policy:
        condition: on-failure
    env_file: ./airflow-home/common.env
    ports:
      - 8080:8080
    volumes:
      - ./airflow-home:/opt/airflow
    depends_on:
      - scheduler
    networks:
      - airflow
  scheduler:
    image: apache/airflow:2.0.0b3-python3.7
    entrypoint: bash
    command: /opt/airflow/startup.bash scheduler
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file: ./airflow-home/common.env
    volumes:
      - ./airflow-home:/opt/airflow
    depends_on:
      - localdb
    networks:
      - airflow
  localdb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow123
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    networks:
      - airflow
networks:
  airflow:
