version: "3.8"
services:
  initdb:
    image: apache/airflow:1.10.12-python3.7
    command: initdb
    volumes:
      - ./airflow-home:/opt/airflow
  webserver:
    image: apache/airflow:1.10.12-python3.7
    command: webserver
    deploy:
      replicas: 1
    env_file: ./airflow-home/common.env
    ports:
      - 8080:8080
    volumes:
      - ./airflow-home:/opt/airflow
    depends_on:
      - initdb
  scheduler:
    image: apache/airflow:1.10.12-python3.7
    command: scheduler
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    env_file: ./airflow-home/common.env
    volumes:
      - ./airflow-home:/opt/airflow
    depends_on:
      - initdb
