version: "3.8"
services:
  webserver:
    image: apache/airflow:1.10.12-python3.7
    entrypoint: bash
    command: /opt/airflow/startup.bash webserver
    deploy:
      replicas: 1      
      restart_policy:
        condition: on-failure
    env_file: ./airflow-home/common.env
    ports:
      - 8080:8080
    volumes:
      - ./airflow-home:/opt/airflow
    depends_on:
      - scheduler
    networks:
      - airflow
  scheduler:
    image: apache/airflow:1.10.12-python3.7
    entrypoint: bash
    command: /opt/airflow/startup.bash scheduler
    deploy:
      replicas: 1      
      restart_policy:
        condition: on-failure
    env_file: ./airflow-home/common.env
    volumes:
      - ./airflow-home:/opt/airflow
    depends_on:
      - localdb
    networks:
      - airflow
  localdb:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow123
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - airflow
networks:
  airflow:
